### ISSUE TITLE
verify signature via ethereum 

### ISSUE THREAD

**Issue by jawndiego** [entropyxyz/sdk#204]
during a successful return: 

Signature: {"Ok":["66WmR2vX+Kap0jeHdyygarjEQrsysAimb2SOSeOfFeW/4Zjr1BzwKxQXoKzKwot2mPgiEtSuEquiVR+lJ2LQowA=","b6a42487271aeaf3d5737536ab1cec8217bf18847c160f4c2b1767bda99a68790c1d26458f2f64f3cd778cbc8f06283b0a319da84a5fcb3818b47d93fe779a80"]}

we can send the first value of our return to ethereum for validation.

**Comment by frankiebee** [comment]
closing in favor of: https://github.com/entropyxyz/cli/issues/14
