### ISSUE TITLE
public entropy accounts

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/sdk#219]
right now we only have `Permissioned` accounts implemented. `Public` accounts do not require a signing key and instead take a param in the encrypted message called address(? cc @JesseAbram). This also does not use encrypt_and_sign and only needs to be encrypted to the threshold server so this is blocked by https://github.com/entropyxyz/x25519-chacha20poly1305/issues/13

**Comment by mixmix** [comment]
done
