### ISSUE TITLE
Use HPKE-js

### ISSUE THREAD

**Issue by JesseAbram** [entropyxyz/sdk#305]
As we move hpke may be worthwhile to investigate using this https://www.npmjs.com/package/hpke-js instead of wasm

**Comment by frankiebee** [comment]
@ameba23 do we still need to do this or is your entropy lib HPKE a fine enough solution?

**Comment by ameba23** [comment]
> @ameba23 do we still need to do this or is your entropy lib HPKE a fine enough solution?

No - i would say we dont need this now as we are using the implementation from `entropy-protocol`.
