### ISSUE TITLE
why are we bundling?

### ISSUE THREAD

**Issue by mixmix** [entropyxyz/sdk#311]
looks like tsup is making bundles of the source code which include all our dependencies

Questions:
1. what is this aiming to achieve?
2. why does the config have multiple entry points? (I could be naive)
    ```js
        entry: [`src/index.ts`, 'src/keys/index.ts', 'src/utils/index.ts', 'src/utils/crypto.ts'],
    ```
3. as it's written, it seems like regardless of whether I want browser code in here the bundle includes browser code. Is that write?

I get converting from ts => js / mjs
I don't get why we want all the source code in all those chunks. It would seem to bloat the install, make our [security audits look bad](https://socket.dev/npm/package/@entropyxyz/sdk/alerts/0.1.4?alert_name=obfuscatedFile), and take bundling control away from me the end user?

**Comment by frankiebee** [comment]
we are no longer building node modules in the latest release. We just did `build-chain` investigations poking this issue to see if we've resolve any of these questions in are chat.

**Comment by frankiebee** [comment]
Closing cause done!
