### ISSUE TITLE
Derive Substrate keys from the user's threshold keyshare

### ISSUE THREAD

**Issue by jakehemmerle** [entropyxyz/sdk#4]
## Overview

We can derive our constraint key from the keyshare and a password using a key derivation function.

I propose
1.  Argon2 with a standardized key-derivation configuration (this might be different than the password-storing configuration but I digress)
2. Hash the threshold keyshare with SHA3-512 or BLAKE2, as Argon2 supports salts up to 64-bytes.
3. Define some secure password requrements (at least 8 chars, uppercase lowercase etc)
4. Stabilize this as an RFC or EIP (entropy improvement proposal) or something 
5. Never write the derived keys or password to disk

## Questions

- Are there any cryptographic APIs we can take advantage of?
  - Web Crypto API would be ideal but algos suck, but it doesn't support sr25519 or even ECDSA-Curve25519, and the only worthwhile KDF is PBKDF2.
- How do we handle keys in the browser? 
- Should we write in Rust/no-std instead of TS so we can try to reuse it in mobile?

**Comment by frankiebee** [comment]
closed no longer valid
